import Container from '@/components/Container';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { Inter } from 'next/font/google';
import './../globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'MeowketPlace',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='grid grid-rows-[auto_1fr_auto] min-h-dvh'>
        <header className='shadow-sm py-1.5 sticky top-0'>
          <Container>
            <Navbar />
          </Container>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
